# Generated by Django 5.2.6 on 2025-10-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizattempt_answers_quizattempt_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor')], default='student', max_length=10),
        ),
    ]
